---

- name: EnableServices
  service:
    name: "{{ item.svc }}"
    enabled: yes
  with_items: "{{ k8s_services }}"
  when: "item.svc is defined"

- name: RestartServices
  service:
    name: "{{ item.svc }}"
    state: restarted
  with_items: "{{ k8s_services }}"
  when: "item.svc is defined"
